apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBHKX0ZCpRUcgXiglDoyPxNifPJy7HKAP/JhEfWxFa+mr38GYsCMGkQadD16tjQEnpW/c4ZyhX+4NIfNYlUt+hR5kt4bD1ihsE9++8iy8Fmb36mJ4qZbLiLFPQE8SUgVGrBkCXp4lGPNFl/a0J4rN5/pF71cdE0EvJFuksYJ2+CgjDhoE4e6LPS8js171zbyD1LdOhUUHV5Iks2Z2nuzAXPJJLuOswWiahftehUTZY6hRmSOWfsO1zi9DK+kFxZxpjLltmtA+VTx9gXSjfk3wxxG0JelTFpREFcsGzPb9b7AcGBWgDMZMhwBPcDGRAK95WKuE7lwn04zMUWzK9btJE0z77iUsznKoPrTKI2/VZk5kZuDJnk2V7CAdD5IkGxyWs8SdQZ1tZGQWor/fvMMQAKP8Gtj8KRYKGryOePgbgUUAcwFMNkg7KB8DdODgPEEtTMphMvkL6rqZ9wBDhWQSmlw8zovxYXEubpghWr/mPJDixZD/U82As9/vk/vLZlFMpdb8yL49gaQZSg0c3jorM6OBLtpyuViSrVmULEmwCAxnH0yHDQ+ETj0xNz4OKz4gOX4pwnXJKIpzxPyakc/yWSMoB2tj0sJmCDmfg8pzVdo4SeRsogZz7sdfQCTJ0572FnJC/qYdTMJIlqxq0QIuntl0DQPEI3zCGlpxnUST8RLwWDHcGGEcq27hYuIZCpo9EmhsPjQqhcXirVkz/+nx7LFYvyFQ0RUHxu42VYQsV7H1LWcRUcOT8tD77kmT9eCMX2VZ09vJskY12CV8iUVhlhZR/6Lc1fy0A3rfm//n16BpHPymrZ98Y9EcEGWM+RXEY0ymSu7uIZQ0Df58BYlwxBCKgYswmB1GOy1PlC+kFJ1UqvtzJ3MnB/L9Ir3CR3WCzpbAECzPjZwFBF
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

