apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBKNhJSwmFpLYqODJBnu+QW/kMAMNkZ34QNUuYqsO7jPTkU+akj+w1jpbGPkqjOyrZ+LRq3XzcuYKxpRSuLOi3poHeZQ+i+ES9l68TVYeaABhyO4AB0qC9xXQnCiOYqMdjNoBM6WH/GhuWS+lvDD/6h79e5n7UHwXrMWvU588D7wjJZHqLiis1zfiPm0r11r8KRmuNFea6EYsRe6I5I6AMiMQUVVp5wWDgfWDvM6Nh7gblmXb4HeouxoYc1FjSf++MOVPpUzqJ0JZMjDif20mzFDSs3Vtj3GK+aU6d3Bk/qvOfNZ+y/tutZuMhR449nKqRzp6RQrn33AhZoeEug9rP1W/aFBMqI1Yk8RB419K/WeUih5IiOqTdUQdlcuW+VN731dJIaz3qAB3dRGFgBL4QBxcsWIxM8LsvbUk0JGKo+gkOAcj/DCLah0DbAyJF0Q11F/mN77spHPmLCvB6pSMMxfdKLSvHOL7BlHShcVgTOEYIme/VsgTvkDVy9AhSSvKWpE5GyYDWAwW2YFST/e7GJGd1q3RUKEkZfHytyjMfwhjeBURBAT0tnE5xjWlGH37dg4kJhE0rOzXvtkBHwgMtkeoyKEsSkHmbVWqcoGROFW/pAtBNXbhC4xcTYq1ZE5GNoCmUNjPs2HDUsOQzSmzo7G5rfVYGBr/e/kUfnbZn0/Lv9nuTPq8SIkp2U9SvttoEpwtkkc6ogR5BLW+dhziHH9qjajVkBuWLPfNCM/WtrCRhujrFkIIxg5tIQEJI31bdcG4o9Pw8wQeM2QftvOhxYc7mlwgxtd+9XTFKJwAmpDY3YGkmSpoIDTv5/pNYVH9r14k9S8rrRoDAyLNV9QYuJ8bH7EIQMCtFs6WIj5voJwiM7PotKwnHXjdsObWVxBNsZd1mQA4EEh9CC
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

