apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBuSo0pLQEqf7E1tW/Hn1CQF8iaxIn+7yg5jAhO0+VpQxz8pbV4YJOhufZhEuC3/XH5oNB9ymEAJVOkTNikmi3J8GP/zNfHHX5lFmPSf+mh0pJ2R7L2u/EH+4spY7hiJ+6KIljwlLDPcipEvqpXG6cNoT9zV0e3LQ25QfPWgf5zCodWeoHAU28RR0tBIl2PMLd7WDeYH7oQF2aMpOBUxv1i7m4t12A8k7IFxBvqOkv0h4UNDu7MQTzx3WfbC5FfIMn96oVwt0y2b6EJDKyGbmBvabUc7CJ+LEZTLtnIDuQ/ImyN2cGpbKvlYHjCIo/B8Hmzo4MZqCVMjZ5dArCaztQw7M4TaDlUje4gAH2h2OroC73A2u1VXg4+9iElHPBMe7TqVG96heBrRCGycVL+pxda5QDahgEp/nt2Wwv/ggMX2+DMj/S1+l6w1Zd55X4QZhHKrPeSt+aWvI4lU6wkurFmSDM4LQljpEJ4XTcKh7qIo/PNhMxyhhvt1d6YmW9emcgd4K4z98ZV9I+leAk9moIbPHLVSnAp5mDyhgHbubhrlSAvFmKPAA4an2P2vxgHo8Zr/6NLJ5toa7IRggJTj+vTAT0yADyD04T3svjYMiPJzMOPwVONqbo8VFE2ZQu0nr7M4eDBVljb5FmCsIxopFJ3UdoA0z17lgI75FMKZOEEhhbu7g6kfj9xKK0nG/AtmFQkEhY1maN6CdNeZAsjkY6FAj1r1FPCprUfD9R5WGAJDoR2Z6bkuJUTOU/UuItlyR+11m+pU29lRMIyy0ysorZOXYTxtFRve7GnsBBssTShxXKcv2qdUwr3Y/IGMejj9OH8RS//nmY6iXeQrNzkOpTdaM4Sx2Cf6ee2w+NZzYx1VYLXb1ZExwgnUMWVCtIZ5HmqmIUPiJrGzvG5
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

