apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCqxk21Rv0pbBrdlK7TICKNyyHNpCsSvYuDxQThLQjPH9JCZV1roATn8QvPfi4d9QsroNGgRVS6MRrDeN12vR3YqBB262NBXV5OZ+wcPqxEsl2nC48d7Uf+cYOw0xBuJQKX6zgbs7JJtsEuP9H95k1RvZU1M4L/RoDIpPEKvwZSiMa7zwjY3WPvPGFwkAoIh0Xz0ocAkJs7S2QCNlNSOCsTpNDPFCYl1wre1qTzUHHWE4K6IbMIMUreUJPU90dKpUv2XW0MFuobvdixqZHYEILvoGqU50Z80IKNSrMJA2As6Xb3c3eZAGOPSZ2m88+eoTsESvlncwW9yAq9cu31/3QhCeSmg12l1rsDqhyaAKaHR3bdz6R+bga/yVnr7AsiSU8nDHV96l6LWowlqJhVQpUSNHm6akuZzjEsmMgfCVFJHUVq/BzoENVeRK8w8qDZ00H2XWjXJK+YtOr4k7L/OFpQMPj/jvBWMe0zo2w3IX+99ux8nRDNGb5vIlmGtv6KHq3pdgDWQn+cBcNGZElk5J+1a3BYZypCsYxXuBgGA2e+C2nijYZiJQx+UoK2jdKRUvOEinI3LY2chYS956PHZwfOxbpJZHKqR6pSSuQD8EqeOKBcb4mU5sRJ+W0iu8CjcThEhxhPdzCSdBV7rN37wsOnRaE2zKWk9Hu6kBQPHiwAgBDomUH2mDvyBnUCElMgEMXO4bLKigww5nmGUYgWHbddDJbEv2WGa/JUqERTMAGgJL8tCH/ZzZol
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

