apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgC1Jj/EHwpjsf8AWdZ9NJ9IqRfNEzFYmJIs2mU/NdnS5aR2q/pZGyu+a+9gKY7rRkoaUerxDCwVANaLxWSwwpYBem5fE4k73TKMQcUzm9jYk4CYkU65WEDJbLadHQWRW1EdrSXhREcjlKHWXkebLE9rcHLTv7BWw0J/bKl6wwbPxlwyjjDonDpGnOi64xMsVFrvN4VIYI8xMST6onYpJkuIwLrMc9/tQoKNWMB/iXlAYkImiRMIk1c+xXLRM781R18DGASv+ZZFd47sZA3QhurUMu+IQIjAub1N0ZhCs1uoR3WXP7hGLAn+0/CHA5tSh+RXpfB+ZrRXpgpx1jTxEYKiB1VsvGTzBqnKWYbfUicdiKpaAYNWCrBN+W0XFbrxk+vUGwv/BdLBW8YMHpKPJU2Fj7gcil8wEmMAM/IaQgmGdbnp+aLnFFqHsCcjNf7OXTQw+2TphVWEq/y6Bh5QK9/Ltrwt1u0jzAd+149BTDeeEIXCT8FgdfU+wWjLpqSHO4YlIlEHC9rRfBhu+IuQtpbGdKZEctzZsDeAQi9VtpV/+iKyigixtox07ntiSOqjAWr0XN7rQCVRlpPrdDDL2A4o8La0J5xogxKYEzgV42z6KpCmz7HXKJyZEytp23WjBETr6SQr04Ln3/Wau6ouX3XfRrnmUsAejuBrMwpjlgilZHilr+nfrG6CrQmv9GMlqJQphjyQZdfN0HSZYH5cZpQewuW1WNEEMIhwP8kPtYs71f/pg3gaOQNH
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

