apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBnFNWqQi+nfjIHOpIlgATX+0UplQkDulGuFgF50UEt7imux4Uz7wj+YBAMpoggDM0aan204fFadCXYp24xkM4vssrd+afF3tn5kyxz8/whLX6Y18COj1IlqArBxpBPDIe33T6CR9UAm7xT8Nk5f14xJ7WqKuTCqmSzAOo7uBPeKMdvXG8TKzZny7a56fLuy5JO3AERUslJDDjubBjzMFAha/gOQ8uMfVBEdb6ee9unmVFX0lDmHcO1Jqpn3mw1MZ9iuniWz6XvACYezXIDWLBCpm6RB1i2f+zmiaRGRyh/E0QKGUH4UNAMVe4Usi1exR/zvZw+fS1lczODI8bre+n3SPsxKkPS+Ws2o6s/BJghkOWZSTXbyJUI+ap+lFYS/VbHZBkCLP2avihSNVxt6UGMk6Zl8fvvsH+6ggNETljRIhGbdV2SODP0za5h3MMESadaB0yIrddlGpdt7fDF/nVy8AGYd1jIr/QuKcI/4Y/0pnIPT2i28logSJ3RsE3M/kJANueR1Z6Vl0kaksZsT2Zl7akhxb/wc6OQam2h+eLdVgavfCd0NQc2PKD46G0I1jUyVdyv7vMIML6qITyQjvPGzz6zMF0XLNJ4gsVYXHNMyDz67J8qxUxBDlos76ibj/EBzRQBgUSJNJzR3jJpkmsIPErGedfEbIORG2VWQOCMyXhjDC92/DGc2EOcdX41yCQ2IcgAtp7Fbgbi6VkoOfiZ++/dIgv+KhcLuyv39kA8AMzaynSRgFpr
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

