apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAcMzNemI2VH84/m7FTD4zdVZT8x6B9nVJdZoIdJJLnAzivdcEJY5h6Nd5VCRGhErZrXNDa5iSdQohNgAH5Lk00KzV6mqjODIRwABqWxzWteH3dcDmklwUNJjlNrcLjcBWN2LcPZYaa0yiU8OjDscLAdAAx1ANTSo1cfvRzeJ6Yrv5hN3pqcqcqwnHkbOqNgWV12SNfLrqFftFq4ia+sPlHUxLP3nXUH0P76dK5MYh98LnLSQy7vMd2My8TMvCdR6eCWLSYRwjLM2nF74joMI9snPJEut4cX28+zgX3KZat5eIMAviN2ksMR21TLCraMFE4d3uMyteuw9K9+je0UjKpgfiT/4uIPJER7cPk4GMIyNuPTaFhQB4JcZynqUYnSGl/R7qCJ3Qy6yGHdzJGk6tOJzGSwfGXk0JyCWMTusIW6Crx8lPFm5I4EWN5siYVf/0qTvu5cBYxcvzEhHnujocT0Qzvb86YITSy5LJd3mR/KsajiWUUFdnvFTe4yg/Ruljb14OikD3jWeUJtKWb1j5oRBKrFr3BDgbPj03UzXSxvoA99bja8NITaQN8a5JvzNQefM+5zqgjpw1EYIq915uzqmHCkI79EUtrZyQcrMwAcgb1zLwRQUk64YpQUtrcawJZH55DxGFuXQ5IWZmY5iZ5lIBIIan7zeW21d9hZZhl+AIuxZLPI84NmBFyU3XTGbUX77Ci7BXVCf+HhLI5tIBIYvZMjtZHsNt39RWbfse+cdyD+wXEFZP3
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

