apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCl0vR22H8EXTT6ONtONG3ivY0+OmgNLfhgGFJoSYvuUqRFzzGGT/4RRLVajOjTS78BjTtZe7tGKrc9ykt4UwtkyhryVS6ceYjNBBALlIiguEjMg/YeYROR+2a0k2QgvIe0ku7LYVQ/+mviLPBKdMm1P5zCOKf88f1KqDIjg9quNq12Si0VuO+SSGrN9NXD7vN4Opr5R7z4y2PQkivuxoqOEvpoCV6/gSlQWxOi1BcYXw7/f5KEvs0xDRfgmaSvykCj8jBZ6Ls7EhsDH71XNWFcnowpcOphQNp/rEkVcIvzPl4GyBLJxlOLMat55n6yWEhUku7m4va++iX+gyv+O724r/rxsFFn+Xe7bB/byJmLzORy9BviJmwYgSKCahwiB9yMHIhnUCuvuEssAGoYGC1p39qkKbCKO94PvvQ3PAAz8A4UaDqUsC6WzUca2jAcBfQ7nuyfJqKhSDUOHmqLxpoJxJIL0t9oqwAAdu/Mjp7n3whvqleBrVlo6AvN5J+Q5sUk9h2kuvz8bC+lkViobudcwT/ExmazDfhbEazBpGlpw7upLHAjAbGQTk8WV25cCCfjWjRl4XNlGTm5Huev7jqVdNc6ZshmUsCvDEvb5P8PWWK9IjfMS4ScB2QQqd+3Ld9XfkL4MomhVpOAoQmhlnX2OJYniuhbSuqBEUXr2BCAOTegIvo71VHXnDyQ6k75GoXK8wNCRmMl6pOYcuTWE0r5D8I079nrk67wCy1rTL5BcqVcEsL1uiXV
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

