apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgACWVapFSV9wayL1ojOOJAJ+3hScN8n+sF2bVQJ19McouBOxkbe123UaRBEjYYqrpeVV/P31dH4+JYBbtaVyfpYDKv8tVoamimHojhtzS3rlg7YYJsW4oZhKC+zokCtumt+jpjR4q2Z+944atZfVfxCE8KYeqlTXuo5J3+VF+5YZbgHqc9wmh2s9zKGqZ+OrX0iHhvB/d5ZLr0Kf791SDIzLNczcGAjHLiEI3Z6a2wvge1KkofWm6AIR2J02JUAHBWkQseXGyRhh3oT6TDJR42IW2DWxRGL/rvSDOtoBtZ96o/OHywufYGXEc3u8fW2hRsg4L+tjmnsKor4fEg2exFQTtlbaPGXOU2ihvbl52tbZaU/UhvsmTmH05vJGiWpUSiCLxsbmMnFVwW5CMdKMkvJCvxAqSQk0UHetzX7qr29DvZCdk/IqsaHrbHzUrT6ZRgskSuO5Pa5+TZHI3niRoYM0QQKPqVVwX40JElplh5jWI8fAQDTx+qDBMCPCLq1gFwW/zxhuNU7zlB7/spTvxN5SjjCbEbcDI8jRc/fmBHOG7alsy2ondVtUsDC7p+N+FoySZmU1GoVa/mv+1Plh+oIDzh3KhE0DWnUtV9Hta9lbwholykWK3w2Zh5RFVULn8Q8WsBFEqzOO85p7PeTrsM9TpvNhvxf9LIb9fUtqjc9UXUe42jLT292x4pFVdhZifTIgxn8lgn9tUAnXQ2losGUt+C1CB8hLNM1N1qzB7WKZWzvekfoPLg2
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

